<a href="https://colab.research.google.com/github/sahibarneja/ml-basics/blob/master/Final_SDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
print("Import successful")

Import successful


## Importing Packages

In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.linear_model import LinearRegression

## Reading CSV files


In [ ]:
dataset1=pd.read_csv('/content/drive/MyDrive/sdl_project/Bitcoin Cash.csv')
dataset2=pd.read_csv('/content/drive/MyDrive/sdl_project/Bitcoin SV US Dollar.csv')
dataset3=pd.read_csv('/content/drive/MyDrive/sdl_project/Ethereum.csv')
dataset4=pd.read_csv('/content/drive/MyDrive/sdl_project/Litecoin.csv')

# Bitcoin Cash

In [ ]:
dataset1['DATE'] = pd.to_datetime(dataset1.DATE)

In [ ]:
X1  = dataset1[['OPEN','HIGH','LOW','VOLUMES(M)']]
y1 = dataset1['PRICE']

In [ ]:
X1_train , X1_test , y1_train , y1_test = train_test_split(X1,y1,random_state = 0)
regressor1 = LinearRegression()
regressor1.fit(X1_train,y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
print(regressor1.coef_)
print(regressor1.intercept_)

[-4.92977617e-01  6.96815141e-01  8.05870457e-01  5.46871076e-04]
-1.0579741044066964


In [ ]:
predicted_btc=regressor1.predict(X1_test)

In [ ]:
dframe=pd.DataFrame(y1_test,predicted_btc)

In [ ]:
dfr=pd.DataFrame({'Actual':y1_test,'Predicted':predicted_btc})

In [ ]:
regressor1.score(X1_test,y1_test)
print('Root Mean Squared Error:',math.sqrt(metrics.mean_squared_error(y_test,predicted)))

0.9923431675954036

In [ ]:
graph=dfr.head(20)

In [ ]:
plt1=[];
print("Enter open value for the stock prediction")
plt1.append(float(input()))
print("Enter High value for the stock prediction")
plt1.append(float(input()))
print("Enter Low value for the stock prediction")
plt1.append(float(input()))
print("Enter Volumes value for the stock prediction")
plt1.append(float(input()))
print(plt)

Enter open value for the stock prediction
312.18
Enter High value for the stock prediction
289.35
Enter Low value for the stock prediction
312.49
Enter Volumes value for the stock prediction
0.89
[]


In [ ]:
features_btc=np.array([plt1])
print(features)
target_btc=regressor1.predict(features_btc)
print("Predicted price",target_btc)

[[250.      252.47    241.41      0.58693]]


#Bitcoin SV

In [ ]:
dataset2['DATE'] = pd.to_datetime(dataset2.DATE)

In [ ]:
X2  = dataset2[['OPEN','HIGH','LOW','VOLUME(K)']]
y2= dataset2['PRICE']

In [ ]:
X2_train , X2_test , y2_train , y2_test = train_test_split(X2,y2,random_state = 0)

In [ ]:
regressor2 = LinearRegression()
regressor2.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
print(regressor2.coef_)
print(regressor2.intercept_)

[-4.92977617e-01  6.96815141e-01  8.05870457e-01  5.46871076e-04]
-1.0579741044066964


In [ ]:
predicted_bsv=regressor2.predict(X2_test)

In [ ]:
dframe2=pd.DataFrame(y2_test,predicted_bsv)
dfr2=pd.DataFrame({'Actual':y2_test,'Predicted':predicted_bsv})

In [ ]:
print(regressor2.score(X2_test,y2_test))
print('Root Mean Squared Error:',math.sqrt(metrics.mean_squared_error(y2_test,predicted_bsv)))

0.9942214703988519
Root Mean Squared Error: 4.946932492776832


In [ ]:
graph=dfr2.head(20)


In [ ]:
plt2=[];
print("Enter open value for the stock prediction")
plt2.append(float(input()))
print("Enter High value for the stock prediction")
plt2.append(float(input()))
print("Enter Low value for the stock prediction")
plt2.append(float(input()))
print("Enter Volumes value for the stock prediction")
plt2.append(float(input()))
print(plt2)

Enter open value for the stock prediction
637.29
Enter High value for the stock prediction
668.87
Enter Low value for the stock prediction
635.64
Enter Volumes value for the stock prediction
3.90
[637.29, 668.87, 635.64, 3.9]


In [ ]:
features_bsv=np.array([plt2])
print(features_bsv)
target_bsv=regressor.predict(features_bsv)
print("Predicted price",target_bsv)

[[637.29 668.87 635.64   3.9 ]]
Predicted price [663.09669439]


# Ethereum

In [ ]:
dataset3['DATE'] = pd.to_datetime(dataset3.DATE)

In [ ]:
X3=dataset3[['OPEN','HIGH','LOW','VOLUME(M)']]
y3 =dataset3['PRICE']

In [ ]:
X3_train , X3_test , y3_train , y3_test = train_test_split(X3,y3,random_state = 0)

In [ ]:
regressor3 = LinearRegression()
regressor3.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
print(regressor3.coef_)
print(regressor3.intercept_)

[-4.92977617e-01  6.96815141e-01  8.05870457e-01  5.46871076e-04]
-1.0579741044066964


In [ ]:
predicted_eth=regressor3.predict(X3_test)

In [ ]:
dframe3=pd.DataFrame(y3_test,predicted_eth)
dfr3=pd.DataFrame({'Actual':y3_test,'Predicted':predicted_eth})

In [ ]:
print(regressor3.score(X3_test,y3_test))
print('Root Mean Squared Error:',math.sqrt(metrics.mean_squared_error(y3_test,predicted_eth)))

0.993213531283302
Root Mean Squared Error: 6.934725173611677


In [ ]:
graph=dfr3.head(20)


In [ ]:
plt3=[];
print("Enter open value for the stock prediction")
plt3.append(float(input()))
print("Enter High value for the stock prediction")
plt3.append(float(input()))
print("Enter Low value for the stock prediction")
plt3.append(float(input()))
print("Enter Volumes value for the stock prediction")
plt3.append(float(input()))
print(plt3)

Enter open value for the stock prediction
393.93
Enter High value for the stock prediction
402.75
Enter Low value for the stock prediction
390.92
Enter Volumes value for the stock prediction
10.15
[393.93, 402.75, 390.92, 10.15]


In [ ]:
features_eth=np.array([plt3])
print(features_eth)
target_eth=regressor.predict(features_eth)
print("Predicted price",target_eth)

[[393.93 402.75 390.92  10.15]]
Predicted price [400.42208142]


# LITECOIN

In [ ]:
dataset4['DATE'] = pd.to_datetime(dataset4.DATE)

In [ ]:
X4=dataset4[['OPEN','HIGH','LOW','VOLUME(M)']]
y4=dataset4['PRICE']

In [ ]:
X4_train , X4_test , y4_train , y4_test = train_test_split(X4,y4,random_state = 0)

In [ ]:
regressor4 = LinearRegression()
regressor4.fit(X_train,y_train)

In [ ]:
print(regressor4.coef_)
print(regressor4.intercept_)

In [ ]:
predicted_ltc=regressor4.predict(X4_test)

In [ ]:
dframe4=pd.DataFrame(y4_test,predicted_ltc)
dfr4=pd.DataFrame({'Actual':y4_test,'Predicted':predicted_ltc})

In [ ]:
print(regressor4.score(X4_test,y4_test))
print('Root Mean Squared Error:',math.sqrt(metrics.mean_squared_error(y4_test,predicted_ltc)))

In [ ]:
graph=dfr4.head(20)


In [ ]:
plt4=[];
print("Enter open value for the stock prediction")
plt4.append(float(input()))
print("Enter High value for the stock prediction")
plt4.append(float(input()))
print("Enter Low value for the stock prediction")
plt4.append(float(input()))
print("Enter Volumes value for the stock prediction")
plt4.append(float(input()))
print(plt4)

In [ ]:
features_ltc=np.array([plt4])
print(features_ltc)
target_ltc=regressor.predict(features_ltc)
print("Predicted price",target_ltc)